export class QuestionSet {
    examSeqNo: number;
    questionSeqNo: number;
    paragraphQuestionid: string;
    paragraphBodyEng = '';
    paragraphBodyHnd = '';
    paragraphImage = '';
    questionId: string;
    questionBodyEng = '';
    questionBodyHindi = '';
    optionBodyAEng = '';
    optionBodyBEng = '';
    optionBodyCEng = '';
    optionBodyDEng = '';
    optionBodyEEng = '';
    optionBodyAHnd = '';
    optionBodyBHnd = '';
    optionBodyCHnd = '';
    optionBodyDHnd = '';
    optionBodyEHnd = '';
    questionBodyImage = '';
    noOfOpt: number;
    questionAttemptTime: string;
    finalSubmitAns: string;
    subjectId: string;
    optionBodyAImg = '';
    optionBodyBImg = '';
    optionBodyCImg = '';
    optionBodyDImg = '';
    optionBodyEImg = '';
    fullMarks: number;
    negativeMarks: number;
    questionLevel: string;
    chapterId = '';
    courseGroup: string;
    correctAns: string;
}
